version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "${DATABASE_TZ:-UTC}"
    ports:
      - "33060:3306"
    volumes:
       - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

  js:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "${NODEJS_TZ:-UTC}"
      MYSQL_TZ: "${DATABASE_TZ:-UTC}"
      SESSION_TZ: "${SESSION_TZ:-}"
      ENV_TZ_OVERRIDE: "${ENV_TZ_OVERRIDE:-}"
    depends_on:
      - db
